index:
    path:     /
    defaults: { _controller: MainBundle:Home:index }

homepage:
    path:     /home
    defaults: { _controller: MainBundle:Home:index }

confirm:
    path:   /confirm
    defaults: { _controller: MainBundle:Confirm:index}

option:
    path:   /option
    defaults: { _controller: MainBundle:Option:index}

invitation:
    path:   /invitation
    defaults: { _controller: MainBundle:Invitation:index}

privacy_policy:
    path:   /privacy_policy
    defaults: { _controller: MainBundle:PrivacyPolicy:index}

terms_of_use:
    path:   /terms_of_use
    defaults: { _controller: MainBundle:TermsOfUse:index}


forgotten_password:
    path:   /forgotten_password
    defaults: { _controller: MainBundle:ForgottenPassword:index}
